#!/usr/bin/python

from pytoml import load
from time import sleep
from pprint import pprint
from sys import exit

import lib.audio_player as audio_player

# Main loop
def main():
    # Load configuration
    with open("conf/rdio.toml", 'r') as rawconf:
        conf = load(rawconf)
    # Set Initial state state
    pprint(conf)
    state = {}
    state['running'] = True
    state['awake']   = True
    state['volume'] = {}
    state['volume']['static'] = 20
    state['volume']['player'] = 0
    state['volume']['system'] = 0
    state['band'] = list(conf['bands'].keys())[0] # randomish
    state['station'] = conf['bands'][state['band']][0]

    print('---')
    pprint(state)
    # TODO: Load state file from /var/lib/rdio/state.toml


    # Initialize screen

    # Initialize static player
    vlc_static = audio_player.audio_player()
    vlc_static.load('../RadioStatic.mp3')
    # Initialize radio player
    vlc_player = audio_player.audio_player()

    # Run preshow

    # Enter main loop
    while True:
        vlc_static.setvol(state['volume']['static'])
        vlc_static.play()
        vlc_player.load(state['station']['stream'])
        vlc_player.setvol(state['volume']['player'])
        vlc_player.play()

        sleep(120)
        exit(0)
        # Read input
        # Update state
        # Render display

    # Run postshow

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print 'KeyboardInterrupt - Killed(0)'
        exit(0)
