#!/usr/bin/python

from pytoml import load
from time import sleep
from pprint import pprint
from sys import exit

import lib.audio_player as audio_player

# Main loop
def main():
    # Load configuration
    with open("conf/rdio.toml", 'r') as rawconf:
        conf = load(rawconf)
    # Set Initial state state
    state = {}
    state['running'] = True
    state['awake']   = True
    # TODO: Load state file from /var/lib/rdio/state.toml


    # Initialize screen

    # Initialize static player
    vlc_static = audio_player.audio_player()
    vlc_static.setvol(0)
    vlc_static.load('../RadioStatic.mp3')
    # Initialize radio player
    vlc_player = audio_player.audio_player()

    # Run preshow

    # Enter main loop
    while True:
        # vlc_static.setvol(50)
        # vlc_static.play()
        # time.sleep(19)
        break
        # Read input
        # Update state
        # Render display

    # Run postshow

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print 'KeyboardInterrupt - Killed(0)'
        exit(0)
